name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:


    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
      name: Checkout Code
     
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2
      
    - name: Setup nuget
      uses: NuGet/setup-nuget@v1.0.5
      
    - name: Restore Packages
      run: nuget restore Rhino.Etl.sln
      
    - name: Build and Publish Web App
      run: msbuild Rhino.Etl.sln /p:Configuration=Release /p:DeployOnBuild=true /p:PublishProfile=FolderProfile
    
    - name: Upload Artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: published_webapp
        path: src\Rhino.etl.core\bin\Release
